import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./App.tsx', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        primary: { DEFAULT: '#4900cc', container: '#6134e3' },
        'on-primary': { DEFAULT: '#ffffff', container: '#f0e6ff' },
        secondary: { DEFAULT: '#8935b6', container: '#f3e5f9' },
        'on-secondary': { DEFAULT: '#ffffff', container: '#3b1558' },
        tertiary: { DEFAULT: '#a8275a', container: '#fce4ec' },
        'on-tertiary': { DEFAULT: '#ffffff', container: '#5c0a28' },
        surface: {
          DEFAULT: '#fcf8ff',
          dim: '#ddd6e5',
          bright: '#fefbff',
          'container-lowest': '#ffffff',
          'container-low': '#f7f0fc',
          container: '#f1eaf7',
          'container-high': '#ebe4f2',
          'container-highest': '#e5deec',
          tint: '#4900cc',
        },
        'on-surface': { DEFAULT: '#1c1a22', variant: '#49454f' },
        outline: { DEFAULT: '#7a757f', variant: '#cbc4d0' },
        error: { DEFAULT: '#d32f2f', container: '#fce4ec' },
        'on-error': { DEFAULT: '#ffffff', container: '#5c1010' },
        success: { DEFAULT: '#2e7d32', container: '#e8f5e9' },
        'on-success': { DEFAULT: '#ffffff', container: '#1b4d1e' },
        warning: { DEFAULT: '#f57c00', container: '#fff3e0' },
        'on-warning': { DEFAULT: '#ffffff', container: '#5c2e00' },
        info: { DEFAULT: '#6134e3', container: '#f0e6ff' },
        'on-info': { DEFAULT: '#ffffff', container: '#1c0066' },
        'map-pin': {
          1: '#4900cc',
          2: '#a8275a',
          3: '#2e7d32',
          4: '#e65100',
          5: '#0277bd',
          6: '#8935b6',
          7: '#00838f',
          8: '#ad1457',
          9: '#4e342e',
          10: '#37474f',
          11: '#f9a825',
          12: '#546e7a',
        },
      },
      fontFamily: {
        inter: ['Inter'],
      },
      fontSize: {
        'display-lg': ['56px', { lineHeight: '63px', fontWeight: '700', letterSpacing: '-1.12px' }],
        'display-md': ['44px', { lineHeight: '50px', fontWeight: '700', letterSpacing: '-0.88px' }],
        'display-sm': ['36px', { lineHeight: '42px', fontWeight: '600', letterSpacing: '-0.54px' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-md': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-lg': ['22px', { lineHeight: '28px', fontWeight: '600' }],
        'title-md': ['18px', { lineHeight: '24px', fontWeight: '500', letterSpacing: '0.18px' }],
        'title-sm': ['16px', { lineHeight: '22px', fontWeight: '500', letterSpacing: '0.16px' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400', letterSpacing: '0.24px' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400', letterSpacing: '0.21px' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400', letterSpacing: '0.24px' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '500', letterSpacing: '0.14px' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500', letterSpacing: '0.6px' }],
        'label-sm': ['11px', { lineHeight: '16px', fontWeight: '500', letterSpacing: '0.55px' }],
      },
      borderRadius: {
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        full: '9999px',
      },
      boxShadow: {
        sm: '0 4px 16px -2px rgba(73, 0, 204, 0.08)',
        md: '0 8px 30px -4px rgba(73, 0, 204, 0.10)',
        lg: '0 16px 48px -8px rgba(73, 0, 204, 0.12)',
        xl: '0 24px 60px -12px rgba(73, 0, 204, 0.15)',
      },
    },
  },
  plugins: [],
};

export default config;
