export const colors = {
  light: {
    primary: '#4900cc',
    primaryContainer: '#6134e3',
    onPrimary: '#ffffff',
    onPrimaryContainer: '#f0e6ff',
    secondary: '#8935b6',
    secondaryContainer: '#f3e5f9',
    onSecondary: '#ffffff',
    onSecondaryContainer: '#3b1558',
    tertiary: '#a8275a',
    tertiaryContainer: '#fce4ec',
    onTertiary: '#ffffff',
    onTertiaryContainer: '#5c0a28',
    surface: '#fcf8ff',
    surfaceDim: '#ddd6e5',
    surfaceBright: '#fefbff',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f7f0fc',
    surfaceContainer: '#f1eaf7',
    surfaceContainerHigh: '#ebe4f2',
    surfaceContainerHighest: '#e5deec',
    surfaceTint: '#4900cc',
    onSurface: '#1c1a22',
    onSurfaceVariant: '#49454f',
    outline: '#7a757f',
    outlineVariant: '#cbc4d0',
    error: '#d32f2f',
    errorContainer: '#fce4ec',
    onError: '#ffffff',
    onErrorContainer: '#5c1010',
    success: '#2e7d32',
    successContainer: '#e8f5e9',
    warning: '#f57c00',
    warningContainer: '#fff3e0',
  },
  dark: {
    primary: '#cfbcff',
    primaryContainer: '#4900cc',
    onPrimary: '#2d0080',
    onPrimaryContainer: '#e9ddff',
    secondary: '#e2b6f3',
    secondaryContainer: '#6a2895',
    onSecondary: '#4a1a6b',
    onSecondaryContainer: '#f3e5f9',
    tertiary: '#ffb2c5',
    tertiaryContainer: '#880643',
    onTertiary: '#5c0a28',
    onTertiaryContainer: '#fce4ec',
    surface: '#141218',
    surfaceDim: '#141218',
    surfaceBright: '#3b383e',
    surfaceContainerLowest: '#0f0d13',
    surfaceContainerLow: '#1d1a22',
    surfaceContainer: '#211f26',
    surfaceContainerHigh: '#2b2930',
    surfaceContainerHighest: '#36343b',
    surfaceTint: '#cfbcff',
    onSurface: '#e6e1e6',
    onSurfaceVariant: '#cbc4d0',
    outline: '#958e99',
    outlineVariant: '#49454f',
    error: '#ffb4ab',
    errorContainer: '#93000a',
    onError: '#690005',
    onErrorContainer: '#ffdad6',
    success: '#a5d6a7',
    successContainer: '#1b5e20',
    warning: '#ffcc80',
    warningContainer: '#e65100',
  },
} as const;

export const mapPinColors = {
  music: '#4900cc',
  nightlife: '#a8275a',
  performing_arts: '#2e7d32',
  food_drink: '#e65100',
  sport_fitness: '#0277bd',
  arts_culture: '#8935b6',
  education: '#00838f',
  festival: '#ad1457',
  business: '#4e342e',
  family: '#f9a825',
  wellness: '#37474f',
  other: '#546e7a',
} as const;

// react-native-vector-icons/MaterialCommunityIcons glyph names, one per category.
export const categoryIcons: Record<Category, string> = {
  music: 'music',
  nightlife: 'glass-cocktail',
  performing_arts: 'drama-masks',
  food_drink: 'silverware-fork-knife',
  sport_fitness: 'dumbbell',
  arts_culture: 'palette',
  education: 'school',
  festival: 'party-popper',
  business: 'briefcase',
  family: 'human-male-female',
  wellness: 'spa',
  other: 'dots-horizontal',
};

export const categories = [
  'music',
  'nightlife',
  'performing_arts',
  'arts_culture',
  'sport_fitness',
  'food_drink',
  'education',
  'business',
  'family',
  'festival',
  'wellness',
  'other',
] as const;

export type Category = (typeof categories)[number];
